INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Плитка', 1);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Двери и Арки', 1);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Окна', 1);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Ламинат и паркетная доска', 1);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Садовые конструкции', 1);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Садовая мебель', 2);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Мангалы, грили', 2);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Растения и семена', 2);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Электро техника', 3);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Камины и печи', 3);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Садовая техника', 3);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Мебель для кухни', 4);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Мойки и раковины', 4);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Оборудование для кухни', 4);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Освещение', 5);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Обои', 5);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Хоз товары', 5);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Обогреватели', 5);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Ванны и аксессуары', 7);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Душ', 7);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Унитазы', 7);
INSERT INTO public.producttypecategory (description, "name", generaltype_id) VALUES('testDescription', 'Мебель для ванной', 7);
