INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Плитка напольная', 1);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Плитка настенная', 1);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Керамаргонит', 1);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Клинкер и искуственный камень', 1);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Межкомнатные двери', 2);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Входные двери', 2);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Люки', 2);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Межкомнатные арки', 2);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Раздвижные двери', 2);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Пластиковые окна', 3);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Утеплители для окон', 3);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Подоконники', 3);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Украшения на окна', 3);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Ламинат', 4);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Паркетная доска', 4);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Пробковые полы', 4);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'ПВХ', 4);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Настенный паркет', 4);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Заборы', 5);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Террасная доска', 5);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Винтовые сваи', 5);
INSERT INTO public.producttype (description, "name", producttypecategory_id) VALUES('testDescription', 'Теплицы', 5);
